#=====================================================#
#================= Configuration v2 ==================#
#=====================================================#

#=================== Global configuration ============#
#url=https://www.google.com/
#url=https://ui.cogmento.com/
url=https://dsuat.icicibankltd.com/
capabilities.browserName=Chrome
capabilities.browserVersion=*
selenium_url=http://localhost:4444/wd/hub
custom_capabilities=NULL
extra_capabilities=NULL
app_version=
ignore_ssl=true
chrome_args=--disable-notifications
headless=false
#=====================================================#

#=============== Environment configuration ===========#
env=DEMO
DEMO.base=https://www.gsmarena.com
DEMO.api_url=https://jsonplaceholder.typicode.com
STAG.api_url=
DEMO.soap_url=https://www.crcind.com:443/csp/samples/SOAP.Demo.cls
#=====================================================#

#============== Locale Configurations ================#
locale=en_US
localization_testing=false
localization_encoding=UTF-8
language=en_US
#=====================================================#

#================ Retry configuration ================#
#number of extra retries to execute tests until pass
retry_count=0
#=====================================================#

#============== WebDriver configuration ==============#
explicit_timeout=10
default_timeout=60
page_load_timeout=60
#number of extra retries to start driver session and interval in seconds
init_retry_count=0
init_retry_interval=1
retry_interval=10
thread_count=2
#=====================================================#

#uncomment and change udid and deviceName for Android test
#============ Android Local Mobile ===================#
#selenium_url=http://localhost:4723/wd/hub
#capabilities.automationName=uiautomator2
#capabilities.deviceName=<phone_name>
#capabilities.udid=<phone_udid>
#capabilities.deviceType=phone
#capabilities.platformName=ANDROID
#capabilities.app=https://qaprosoft.s3-us-west-2.amazonaws.com/carinademoexample.apk
#=====================================================#

#uncomment and change deviceName and platformVersion for iOS test
#======== Local Run for iOS Mobile ===============#
#selenium_url=http://localhost:4723/wd/hub
#capabilities.platformName=iOS
#capabilities.deviceName=<simulator_name>
#capabilities.deviceType=phone
#capabilities.platformVersion=<simulator_platform_version>
#capabilities.automationName=XCUITest
#capabilities.udid=
#capabilities.app=https://qaprosoft.s3-us-west-2.amazonaws.com/carinademoexample.zip
#=====================================================#

#================ Report configuration ===============#
core_log_level=INFO
auto_screenshot=true
project_report_directory=/reports
custom_screenshot=true
custom_project_report_directory=/ICICIForex_Reports
#custom_project_report_directory=/Users/kaveri.keer1_qua/Downloads/cogmentoCrm/reports
#custom_project_report_directory=D://IDFC//cogmentoCrm_Updated//cogmentoCrm//reports
#custom_project_report_directory=./reports
customerName=ICICI
projectName=Forex Trading
report_url=.
max_screen_history=10
result_sorting=true
email_list=NULL
suite_name=web
#=====================================================#

#=============== MyBatis configuration ===============#
mybatis_cnfg=mybatis.config.xml
mybatis_env=testing
#=====================================================#

#====================== TestRail =====================#
testrail_milestone=NULL
testrail_assignee=NULL
#=====================================================#

#===================== Amazon ========================#
s3_bucket_name=NULL
access_key_id=NULL
secret_key=NULL
#=====================================================#

#===================== Azure =========================#
azure_account_name=NULL
azure_blob_url=https://${azure_account_name}.blob.core.windows.net
azure_access_key_token=NULL
azure_local_storage=NULL
#=====================================================#

#===================== Crypto ========================#
crypto_algorithm=AES/ECB/PKCS5Padding
crypto_key_type=AES
crypto_key_size=128
crypto_key_path=./src/main/resources/crypto.key
#=====================================================#
password={crypt:8O9iA4+f3nMzz85szmvKmQ==}
credentials=test@gmail.com/${password}